---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

My name is Pavithra Srinivasan and I am from Seattle, WA. I moved to New York to start the MS Epidemiology program at Columbia University. I went to undergrad at Baylor University, and then worked at a public health agency shortly after. My goal is to pursue higher degrees for both academic and professional growth. I love to dance, cook and go on hikes in my free time. Take a look around my website to learn more about me. 

## Education

* Baylor University – Waco, TX 
Aug’ 2014 - Dec’ 2018 ; Bachelor of Science in Biology, and Minor in Sociology 

* Columbia University, Mailman School of Public Health - New York City, NY			       
Sept’ 2023 - Present ; Master of Science in Epidemiology

## Professional Experiences

* National Foundation for the Centers for Disease Control and Prevention (CDC Foundation)		
Role: Infectious Diseases Program Specialist								       
Dates: Jan’ 2022 – Jan’ 2023
5 Global and Federal Portfolios under Vaccine Preventable Diseases (VPD)

* Milken Institute School of Public Health at The George Washington University
Role: Global Health Academic Administrator
Dates: Jan'2020 - Aug 2021

## Licenses and Certifications

* Graduate Certificate in Public Administration – Seattle University 					     	
* Informed Consent Certification – The Global Health Network						
* Good Clinical Practice – NIDA Clinical Trials Network								
* Program Management for Development Professionals (PMP for Nonprofits) - Humentum				
* COVID-19 Contact Tracing - The Johns Hopkins University – Coursera 						

## Skills
* Excel, PowerPoint, Word, Outlook, Teams, SharePoint, Salesforce, SmartSheet, NetSuite, Oracle, Zoom, Sophos, Mailchimp and Canva.
* Functional in SPSS, R-programming and Dedoose. 
* Other interests: travel, hiking, dance, and concerts



